### ISSUE TITLE
running a container in detach mode is being stopped

### ISSUE THREAD

**Issue by GabyCT** [clearcontainers/runtime#328]
While running a container in detach mode, the container gets stopped

 Running in detach mode
cc-runtime run -d --bundle /home/cloud/rootfs --console /dev/ptmx containerone

 Check container state
 cc-runtime state containerone
{"ociVersion":"1.0.0-rc5","id":"containerone","status":"stopped","pid":23049,"bundle":"/home/cloud/rootfs","annotations":{"com.github.containers.virtcontainers.pkg.oci.bundle_path":"/home/coud/rootfs","com.github.containers.virtcontainers.pkg.oci.config_path":"/home/cloud/rootfs/config.json","com.github.containers.virtcontainers.pkg.oci.container_type":"pod_sandbox"}}
Check again container status with list command

cc-runtime list
ID                     PID         STATUS      BUNDLE                 CREATED                          OWNER
containerone           23101       stopped     /home/cloud/rootfs     2017-07-17T08:14:51.724016463Z

This is with version
cc-runtime  : 3.0.0-alpha.3
 OCI specs: 1.0.0-rc5

On ubuntu 16.10

**Comment by sboeuf** [comment]
@GabyCT Please remove the --console /dev/ptmx and this should work.

**Comment by grahamwhaley** [comment]
Just to note - before we just remove that, we should check what happens with runc etc. and ensure we are functionally the same I think. Otherwise we might end up hiding a (should never happen, but...) corner case.

**Comment by jodh-intel** [comment]
@sboeuf - how about we add a check to the runtime so that if `-d` and `--console` are specified, we error?

**Comment by grahamwhaley** [comment]
I'm prone to ask what the spec says is acceptable and what we should do (and sure, I suspect the answer might be that it does not say...), and also what runc does - we should understand both of those before we make a choice I think.

**Comment by sboeuf** [comment]
@grahamwhaley Well the spec does not say anything since this is about `run`. Thus, the reference is about runc, but runc recently moved to `--console-socket`, you're not supposed to provide `--console` anymore. But we still want this option for our runtime since we still want the backward compatibility with Docker 1.12 -> 17.05.

@jodh-intel we still want to be able to provide a console and start as detached IMO. That's actually the only way (console or console-socket) to get some output if you go as detached. But this particular case is about giving `/dev/ptmx` as a console path, which was kind of a hack on our side because we were expecting the runtime to create a pty pair for us. If you look at runc 1.0.0-rc2 (the version with the support for `--console`), you have to provide a slave path from an existing pty pair. It is not creating something for you. This means that we should modify this script and:
- Either we don't expect any output and we don't provide any console
- Or we create a pty pair and we read the output from the master end (given the fact that we provided the slave end through the `--console` option).

**Comment by grahamwhaley** [comment]
good summary @sboeuf thx!

**Comment by GabyCT** [comment]
@sboeuf thanks that worked, however, I can see that the terminal gets distorted. Also, I see that after performing the running, the pause, the resume and if you want to kill the container, it does not do it, it always running so it can not be kill and delete it. Is that ok that I close this issue and create another one for the killing the container? Thanks

**Comment by sboeuf** [comment]
@GabyCT Yeah currently we don't have merged all our PRs because of some ongoing discussion here: https://github.com/opencontainers/runc/issues/1525. This is causing the output to still come on the terminal even when you don't specify any console but this is not a big deal right now.
I have noticed the issue your are mentioning and it is caused by the fact that we don't update the container status from a `kill` command, which is expected actually. This is a bug and we need to solve this properly.
My proposal is that you use `cc-runtime state containerone` before you check `cc-runtime list`. The call to `state` should update the status of your container by checking if the shim is still up and running.

**Comment by sboeuf** [comment]
@GabyCT does that work better ?

**Comment by GabyCT** [comment]
@sboeuf yes I did that however I still have the issue that the containers can not be deleted it.

cc-runtime run -d  --bundle /home/cloud/rootfs/ test

 cc-runtime state test
{"ociVersion":"1.0.0-rc5","id":"test","status":"running","pid":21594,"bundle":"/home/cloud/rootfs","annotations":{"com.github.containers.virtcontainers.pkg.oci.bundle_path":"/home/cloud/rootfs","com.github.containers.virtcontainers.pkg.oci.config_path":"/home/cloud/rootfs/config.json","com.github.containers.virtcontainers.pkg.oci.container_type":"pod_sandbox"}}

cc-runtime delete test
Container still running, should be stopped

**Comment by GabyCT** [comment]
@sboeuf if you want I can close this issue and create another one for delete or killing the container, is that ok?

**Comment by sboeuf** [comment]
@GabyCT But in your example you forgot to kill the container before. Either you kill the container and you delete it, or you delete it with the `--force` flag.

**Comment by GabyCT** [comment]
@sboeuf, I am doing the following 

* Delete option
cc-runtime run -d  --bundle /home/cloud/rootfs/ test

cc-runtime state test
{"ociVersion":"1.0.0-rc5","id":"test","status":"running","pid":21874,"bundle":"/home/cloud/rootfs","annotations":{"com.github.containers.virtcontainers.pkg.oci.bundle_path":"/home/cloud/rootfs","com.github.containers.virtcontainers.pkg.oci.config_path":"/home/cloud/rootfs/config.json","com.github.containers.virtcontainers.pkg.oci.container_type":"pod_sandbox"}}

 cc-runtime delete test --force
ERROR received from Hyperstart

* Kill option
 cc-runtime run -d  --bundle /home/cloud/rootfs/ testtwo

cc-runtime state testtwo
{"ociVersion":"1.0.0-rc5","id":"testtwo","status":"running","pid":21904,"bundle":"/home/cloud/rootfs","annotations":{"com.github.containers.virtcontainers.pkg.oci.bundle_path":"/home/cloud/rootfs","com.github.containers.virtcontainers.pkg.oci.config_path":"/home/cloud/rootfs/config.json","com.github.containers.virtcontainers.pkg.oci.container_type":"pod_sandbox"}}

 cc-runtime kill testtwo
 
cc-runtime state testtwo
{"ociVersion":"1.0.0-rc5","id":"testtwo","status":"running","pid":21904,"bundle":"/home/cloud/rootfs","annotations":{"com.github.containers.virtcontainers.pkg.oci.bundle_path":"/home/cloud/rootfs","com.github.containers.virtcontainers.pkg.oci.config_path":"/home/cloud/rootfs/config.json","com.github.containers.virtcontainers.pkg.oci.container_type":"pod_sandbox"}}

As you can see it still says running

**Comment by GabyCT** [comment]
@sboeuf and even after the kill I tried to do the delete and it is saying

 cc-runtime delete testtwo --force
ERROR received from Hyperstart

**Comment by sboeuf** [comment]
@GabyCT Then maybe you can open an issue explaining what you did and what was not working. I'll give this a try later.
You should also open an issue about the fact that cc-runtime list does not update the container state.

**Comment by GabyCT** [comment]
issue #343 was created
