### ISSUE TITLE
Docs: developer doc page has bit rotted and needs an update

### ISSUE THREAD

**Issue by grahamwhaley** [clearcontainers/runtime#367]
It appears the developer docs at;
https://github.com/clearcontainers/runtime/blob/master/docs/developers-clear-containers-install.md
have rotted a bit, and are out of date.
Two things that occur to me (there may be more...):
- the PKGDIR references `/usr/libexec`, but I think we are now on `/usr/local/libexec` (my install failed as the config.toml did not find the shim for this reason)
- the docker install instrs use the docker runtime name `clearcontainers` for the cc-runtime binary mapping - I have a feeling we are actually now using/recommending cc-runtime=cc-runtime for the docker name/runtime binary mapping

/cc @jodh-intel @sboeuf @gorozco1 for input etc.

**Comment by jodh-intel** [comment]
I've raised #370 for this.

I haven't made any changes on the PR for the runtime name yet. I'm happy with either `clear-containers` (note the dash) or `cc-runtime`. The latter is arguably less obvious (you need to know that `cc-runtime` equates to "Clear Containers"), but since the default runtime (`runc`) name reflects the name of the runtime binary, `cc-runtime` would seem like a better fit for CC 3.0.

**Comment by grahamwhaley** [comment]
I'd vote for shorter docker runtime names rather than longer, so put my preference with `cc-runtime`

**Comment by jodh-intel** [comment]
Agreed. PR updated.

**Comment by gorozco1** [comment]
we set clearcontainers after a talk with @sameo at the irc. The change on the name of the runtime makes sense to me though. +1
