### ISSUE TITLE
Create an issue template

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/runtime#589]
Create an `ISSUE_TEMPLATE.md` to help guide users raise issues.

For scenarios where the template is not appropriate, simply `CTRL-a delete` to zap it ;)

---

# Expected result

# Actual result 

# Details

Please provide the output of the following (either paste into this issue, or attach output as separate files)

- `sudo cc-runtime cc-env`
- `sudo docker info`
- `sudo cat /usr/share/defaults/clear-containers/configuration.toml`
- `sudo cat /etc/clear-containers/configuration.toml` (if it exists)

- If you have logging enabled
  - `sudo cat /var/lib/clear-containers/runtime/runtime.log`

**Comment by jodh-intel** [comment]
@grahamwhaley - since there are a quite a few details for the user to collect here, I think it would be helpful if we instead provided a script (say `cc-collect-data.sh`) so that the user only has to attach a single file (or paste it). What do you think?

**Comment by grahamwhaley** [comment]
I think the idea of a collect script is a good one - that will help avoid any potential finger-trouble as well.
I'm slightly wary about attaching the runtime.log to the Issues - the logs are currently huge, like really huge, so that might not be a great idea - not in its raw and full form anyway. I wonder if we can do a first pass `grep` for keywords (fail, error, warning etc.)

**Comment by jodh-intel** [comment]
Good point. I'll look at writing a script for that ...
