### ISSUE TITLE
burn clear-19710-installer.img.xz failed with error "fdisk: cannot open /dev/mmcblk0rpmb: Input/output error"

### ISSUE THREAD

**Issue by zyuan2x** [clearcontainers/runtime#869]
# Description of problem
follow blow wiki to install the clear linux image on BXT_GP board
https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install 

It happened blow error when work on this step "Choose Clear Linux installation type"
error information: "fdisk: cannot open /dev/mmcblk0rpmb: Input/output error"

Burn the image link: https://download.clearlinux.org/image/clear-19710-installer.img.xz 
Please attachment file: install_failed_on_bxt_gp.jpg

# Expected result
install successfully

# Actual result
install failed

---
![Uploading install_failed_on_bxt_gp.jpg…]()

**Comment by grahamwhaley** [comment]
Hi @zyuan2x - this looks like a `Clear Linux` issue at this stage, rather than a Clear Containers one. I think you will be better posting this request directly on one of the Clear Linux related places listed on this page: https://clearlinux.org/community
which include a mailing list, irc channel, or possibly somewhere in https://github.com/clearlinux on github.
I think the mailing list or irc will be the best portals.
/cc @matthewrsj who might be able to track this?

**Comment by matthewrsj** [comment]
This seems to be a Clear Linux Installer (Ister) bug. I opened an issue to track: https://github.com/bryteise/ister/issues/119

**Comment by zyuan2x** [comment]
Install Clear Linux on BXT_GP:
Result: Installed successfully with the image clear-19810-installer.img.xz
