### ISSUE TITLE
Update Ubuntu install doc for 17.10

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/runtime#881]
Now that Docker have finally released the following:

- https://download.docker.com/linux/ubuntu/dists/artful/pool/stable/amd64/docker-ce_17.12.0~ce-0~ubuntu_amd64.deb

... we need to update and re-test the installation doc for Ubuntu 17.10:

- https://github.com/clearcontainers/runtime/blob/master/docs/ubuntu-installation-guide.md

**Comment by jodh-intel** [comment]
Note that since Ubuntu 16.10 is now end-of-life according to https://wiki.ubuntu.com/Releases, we need to:

- Remove it from the install doc.
- Remove the Ubuntu 16.10 OBS binaries.

/cc @gorozco1, @erick0z, @chavafg, @grahamwhaley, @sameo.

**Comment by GabyCT** [comment]
@jodh-intel , an error occurs when I am trying to add the repository for Docker in ubuntu 17.10
$ apt-get update
Ign:1 https://download.docker.com/linux/ubuntu artful InRelease
Err:2 https://download.docker.com/linux/ubuntu artful Release
Could not handshake: The TLS connection was non-properly terminated.

**Comment by GabyCT** [comment]
@jodh-intel , I was able to run CC 3.0 in ubuntu 17.10 (by installing manually the rpm of docker). However, I can not add the repository of docker in my system mainly because of the problem described it before

**Comment by jodh-intel** [comment]
Hi @GabyCT - Is that error consistent? I've just checked and I'm able to install docker in 17.10 as documented. Could it be related to proxy settings I wonder?

It would be interesting to look at the output of:

```
$ sudo apt-get update -o Debug::Acquire::http=True -o Debug::Acquire::https=True
```

**Comment by GabyCT** [comment]
@jodh-intel , I have the same error when trying to add the repository of docker in ubuntu 17.10. I even used another machine
$ sudo -E apt-get update
Ign:1 https://download.docker.com/linux/ubuntu artful InRelease
Hit:2 http://security.ubuntu.com/ubuntu artful-security InRelease
Err:3 https://download.docker.com/linux/ubuntu artful Release
  Could not handshake: The TLS connection was non-properly terminated.
Get:4 http://archive.ubuntu.com/ubuntu artful InRelease [237 kB]
Hit:5 http://archive.ubuntu.com/ubuntu artful-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu artful-backports InRelease
Reading package lists... Done
E: The repository 'https://download.docker.com/linux/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

When I am doing the
$ sudo apt-get update -o Debug::Acquire::http=True -o Debug::Acquire::https=True
0% [Working]GET http://security.ubuntu.com/ubuntu/dists/artful-security/InRelease HTTP/1.1
Host: security.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
If-Modified-Since: Thu, 04 Jan 2018 16:22:00 GMT
User-Agent: Debian APT-HTTP/1.3 (1.5.1)


GET http://archive.ubuntu.com/ubuntu/dists/artful/InRelease HTTP/1.1
Host: archive.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
If-Modified-Since: Thu, 19 Oct 2017 12:56:35 GMT
User-Agent: Debian APT-HTTP/1.3 (1.5.1)


Ign:1 https://download.docker.com/linux/ubuntu artful InRelease
Err:2 https://download.docker.com/linux/ubuntu artful Release
  Could not handshake: The TLS connection was non-properly terminated.
0% [Waiting for headers] [Waiting for headers]Answer for: http://security.ubuntu.com/ubuntu/dists/artful-security/InRelease
HTTP/1.1 200 OK
Date: Thu, 04 Jan 2018 16:27:05 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 04 Jan 2018 16:25:00 GMT
ETag: "132fd-561f5c5fb0f00"
Accept-Ranges: bytes
Content-Length: 78589
Cache-Control: max-age=3174, s-maxage=3300, proxy-revalidate
Expires: Thu, 04 Jan 2018 17:20:00 GMT
Via: 1.1 fmdmzpr06, 1.1 fmintpr02
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Age: 0

Get:3 http://security.ubuntu.com/ubuntu artful-security InRelease [78.6 kB]
0% [Waiting for headers] [3 InRelease 3660 B/78.6 kB 5%]Answer for: http://archive.ubuntu.com/ubuntu/dists/artful/InRelease
HTTP/1.1 200 OK
Date: Thu, 04 Jan 2018 16:27:05 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 19 Oct 2017 12:56:35 GMT
ETag: "39c6b-55be5e2d806c0"
Accept-Ranges: bytes
Content-Length: 236651
Cache-Control: max-age=0, proxy-revalidate
Expires: Thu, 04 Jan 2018 16:27:05 GMT
Via: 1.1 fmdmzpr06, 1.1 fmintpr02
Proxy-Connection: Keep-Alive
Connection: Keep-Alive

Get:4 http://archive.ubuntu.com/ubuntu artful InRelease [237 kB]
0% [4 InRelease 116 kB/237 kB 49%]GET http://archive.ubuntu.com/ubuntu/dists/artful-updates/InRelease HTTP/1.1
Host: archive.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
If-Modified-Since: Thu, 04 Jan 2018 16:07:00 GMT
User-Agent: Debian APT-HTTP/1.3 (1.5.1)


0% [Waiting for headers]Answer for: http://archive.ubuntu.com/ubuntu/dists/artful-updates/InRelease
HTTP/1.1 200 OK
Date: Thu, 04 Jan 2018 16:27:06 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 04 Jan 2018 16:25:00 GMT
ETag: "132fb-561f5c5fb0f00"
Accept-Ranges: bytes
Content-Length: 78587
Cache-Control: max-age=1673, proxy-revalidate
Expires: Thu, 04 Jan 2018 16:55:00 GMT
Via: 1.1 fmdmzpr06, 1.1 fmintpr02
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Age: 0

Get:5 http://archive.ubuntu.com/ubuntu artful-updates InRelease [78.6 kB]
0% [5 InRelease 3652 B/78.6 kB 5%]GET http://archive.ubuntu.com/ubuntu/dists/artful-backports/InRelease HTTP/1.1
Host: archive.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
If-Modified-Since: Thu, 04 Jan 2018 16:07:00 GMT
User-Agent: Debian APT-HTTP/1.3 (1.5.1)


0% [Waiting for headers]Answer for: http://archive.ubuntu.com/ubuntu/dists/artful-backports/InRelease
HTTP/1.1 200 OK
Date: Thu, 04 Jan 2018 16:27:07 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 04 Jan 2018 16:25:00 GMT
ETag: "119fe-561f5c5fb0f00"
Accept-Ranges: bytes
Content-Length: 72190
Cache-Control: max-age=1672, proxy-revalidate
Expires: Thu, 04 Jan 2018 16:55:00 GMT
Via: 1.1 fmdmzpr06, 1.1 fmintpr02
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Age: 0

0% [Waiting for headers]Answer for: http://archive.ubuntu.com/ubuntu/dists/artfu                                                                                                              l-backports/InRelease
HTTP/1.1 200 OK
Date: Thu, 04 Jan 2018 16:24:38 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 04 Jan 2018 16:22:00 GMT
ETag: "119fe-561f5bb407a00"
Accept-Ranges: bytes
Content-Length: 72190
Cache-Control: max-age=1641, proxy-revalidate
Expires: Thu, 04 Jan 2018 16:52:00 GMT
Via: 1.1 fmdmzpr05, 1.1 fmintpr01
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Age: 0

Get:6 http://archive.ubuntu.com/ubuntu artful-backports InRelease [72.2 kB]
Reading package lists... Done
E: The repository 'https://download.docker.com/linux/ubuntu artful Release' does                                                                                                               not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disa                                                                                                              bled by default.
N: See apt-secure(8) manpage for repository creation and user configuration deta                                                                                                              ils.
root@singlevm:/etc/apt# clear
root@singlevm:/etc/apt# sudo apt-get update -o Debug::Acquire::http=True -o Debug::Acquire::https=True
0% [Working]GET http://security.ubuntu.com/ubuntu/dists/artful-security/InRelease HTTP/1.1
Host: security.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
If-Modified-Since: Thu, 04 Jan 2018 16:07:00 GMT
User-Agent: Debian APT-HTTP/1.3 (1.5.1)


GET http://archive.ubuntu.com/ubuntu/dists/artful/InRelease HTTP/1.1
Host: archive.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
If-Modified-Since: Thu, 19 Oct 2017 12:56:35 GMT
User-Agent: Debian APT-HTTP/1.3 (1.5.1)


Ign:1 https://download.docker.com/linux/ubuntu artful InRelease
Err:2 https://download.docker.com/linux/ubuntu artful Release
  Could not handshake: The TLS connection was non-properly terminated.
0% [Waiting for headers] [Waiting for headers]Answer for: http://security.ubuntu.com/ubuntu/dists/artful-security/InRelease
HTTP/1.1 200 OK
Date: Thu, 04 Jan 2018 16:25:04 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 04 Jan 2018 16:22:00 GMT
ETag: "132fd-561f5bb407a00"
Accept-Ranges: bytes
Content-Length: 78589
Cache-Control: max-age=3115, s-maxage=3300, proxy-revalidate
Expires: Thu, 04 Jan 2018 17:17:00 GMT
Via: 1.1 fmdmzpr06, 1.1 fmintpr02
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Age: 0

Get:3 http://security.ubuntu.com/ubuntu artful-security InRelease [78.6 kB]
0% [Waiting for headers] [3 InRelease 3660 B/78.6 kB 5%]Answer for: http://archive.ubuntu.com/ubuntu/dists/artful/InRelease
HTTP/1.1 200 OK
Date: Thu, 04 Jan 2018 16:25:04 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 19 Oct 2017 12:56:35 GMT
ETag: "39c6b-55be5e2d806c0"
Accept-Ranges: bytes
Content-Length: 236651
Cache-Control: max-age=0, proxy-revalidate
Expires: Thu, 04 Jan 2018 16:25:04 GMT
Via: 1.1 fmdmzpr06, 1.1 fmintpr02
Proxy-Connection: Keep-Alive
Connection: Keep-Alive

Get:4 http://archive.ubuntu.com/ubuntu artful InRelease [237 kB]
0% [4 InRelease 143 kB/237 kB 60%]GET http://security.ubuntu.com/ubuntu/dists/artful-security/main/source/by-hash/SHA256/d81e21215dbd5cf2f85a1949282c656df202fbd25bae2668791c4bed36eed8a4 HTTP/1.1
Host: security.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (1.5.1)


GET http://archive.ubuntu.com/ubuntu/dists/artful-updates/InRelease HTTP/1.1
Host: archive.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
If-Modified-Since: Thu, 04 Jan 2018 16:07:00 GMT
User-Agent: Debian APT-HTTP/1.3 (1.5.1)


0% [4 InRelease gpgv 237 kB] [Waiting for headers] [Waiting for headers]Answer for: http://security.ubuntu.com/ubuntu/dists/artful-security/main/source/by-hash/SHA256/d81e21215dbd5cf2f85a1949282c656df202fbd25bae2668791c4bed36eed8a4
HTTP/1.1 200 OK
Date: Thu, 04 Jan 2018 16:25:04 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 04 Jan 2018 16:16:30 GMT
ETag: "5040-561f5a7951380"
Accept-Ranges: bytes
Content-Length: 20544
Via: 1.1 fmdmzpr06, 1.1 fmintpr02
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Age: 0

Get:5 http://security.ubuntu.com/ubuntu artful-security/main Sources [20.5 kB]
0% [4 InRelease gpgv 237 kB] [Waiting for headers]GET http://security.ubuntu.com/ubuntu/dists/artful-security/main/binary-amd64/by-hash/SHA256/d7714cd5faeef15ebce69161fd7012739f87feb2b2e0bccfadbfe1619a030fda HTTP/1.1
Host: security.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (1.5.1)


0% [Waiting for headers] [Waiting for headers]Answer for: http://archive.ubuntu.com/ubuntu/dists/artful-updates/InRelease
HTTP/1.1 200 OK
Date: Thu, 04 Jan 2018 16:25:05 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 04 Jan 2018 16:22:00 GMT
ETag: "132fb-561f5bb407a00"
Accept-Ranges: bytes
Content-Length: 78587
Cache-Control: max-age=1614, proxy-revalidate
Expires: Thu, 04 Jan 2018 16:52:00 GMT
Via: 1.1 fmdmzpr06, 1.1 fmintpr02
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Age: 0

Get:6 http://archive.ubuntu.com/ubuntu artful-updates InRelease [78.6 kB]
0% [6 InRelease 3675 B/78.6 kB 5%] [Waiting for headers]GET http://archive.ubuntu.com/ubuntu/dists/artful-backports/InRelease HTTP/1.1
Host: archive.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
If-Modified-Since: Thu, 04 Jan 2018 16:07:00 GMT
User-Agent: Debian APT-HTTP/1.3 (1.5.1)


0% [6 InRelease gpgv 78.6 kB] [Waiting for headers] [Waiting for headers]Answer for: http://security.ubuntu.com/ubuntu/dists/artful-security/main/binary-amd64/by-hash/SHA256/d7714cd5faeef15ebce69161fd7012739f87feb2b2e0bccfadbfe1619a030fda
HTTP/1.1 200 OK
Date: Thu, 04 Jan 2018 16:25:05 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 04 Jan 2018 16:16:30 GMT
ETag: "e8e0-561f5a7951380"
Accept-Ranges: bytes
Content-Length: 59616
Via: 1.1 fmdmzpr06, 1.1 fmintpr02
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Age: 0

Get:7 http://security.ubuntu.com/ubuntu artful-security/main amd64 Packages [59.6 kB]
0% [6 InRelease gpgv 78.6 kB] [Waiting for headers] [7 Packages 3755 B/59.6 kB 6%]GET http://security.ubuntu.com/ubuntu/dists/artful-security/main/i18n/by-hash/SHA256/6f38a560dcf862b91ed2bcf991c54ef5530e92f6ecec157434dc375bcccad088 HTTP/1.1
Host: security.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (1.5.1)


0% [Waiting for headers] [Waiting for headers]Answer for: http://archive.ubuntu.com/ubuntu/dists/artful-backports/InRelease
HTTP/1.1 200 OK
Date: Thu, 04 Jan 2018 16:25:05 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 04 Jan 2018 16:22:00 GMT
ETag: "119fe-561f5bb407a00"
Accept-Ranges: bytes
Content-Length: 72190
Cache-Control: max-age=1614, proxy-revalidate
Expires: Thu, 04 Jan 2018 16:52:00 GMT
Via: 1.1 fmdmzpr06, 1.1 fmintpr02
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Age: 0

Get:8 http://archive.ubuntu.com/ubuntu artful-backports InRelease [72.2 kB]
0% [8 InRelease gpgv 72.2 kB] [Waiting for headers]Answer for: http://security.ubuntu.com/ubuntu/dists/artful-security/main/i18n/by-hash/SHA256/6f38a560dcf862b91ed2bcf991c54ef5530e92f6ecec157434dc375bcccad088
HTTP/1.1 200 OK
Date: Thu, 04 Jan 2018 16:25:05 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 04 Jan 2018 16:16:30 GMT
ETag: "6c30-561f5a7951380"
Accept-Ranges: bytes
Content-Length: 27696
Via: 1.1 fmdmzpr06, 1.1 fmintpr02
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Age: 0

Get:9 http://security.ubuntu.com/ubuntu artful-security/main Translation-en [27.7 kB]
0% [8 InRelease gpgv 72.2 kB] [9 Translation-en 5103 B/27.7 kB 18%]GET http://security.ubuntu.com/ubuntu/dists/artful-security/universe/binary-amd64/by-hash/SHA256/610bece7ed706fd78569c66e2b1fa78458fd339a866d64056b2f3f9618068493 HTTP/1.1
Host: security.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (1.5.1)


95% [Waiting for headers]Answer for: http://security.ubuntu.com/ubuntu/dists/artful-security/universe/binary-amd64/by-hash/SHA256/610bece7ed706fd78569c66e2b1fa78458fd339a866d64056b2f3f9618068493
HTTP/1.1 200 OK
Date: Thu, 04 Jan 2018 16:25:05 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 04 Jan 2018 16:16:30 GMT
ETag: "465c-561f5a7951380"
Accept-Ranges: bytes
Content-Length: 18012
Via: 1.1 fmdmzpr06, 1.1 fmintpr02
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Age: 0

Get:10 http://security.ubuntu.com/ubuntu artful-security/universe amd64 Packages [18.0 kB]
96% [10 Packages 6238 B/18.0 kB 35%]GET http://security.ubuntu.com/ubuntu/dists/artful-security/universe/i18n/by-hash/SHA256/7b34bdcf5a84144d4393a374d073f0c6c93c5db56df7cd4349a8ce22db66f09b HTTP/1.1
Host: security.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
User-Agent: Debian APT-HTTP/1.3 (1.5.1)


98% [Waiting for headers]Answer for: http://security.ubuntu.com/ubuntu/dists/artful-security/universe/i18n/by-hash/SHA256/7b34bdcf5a84144d4393a374d073f0c6c93c5db56df7cd4349a8ce22db66f09b
HTTP/1.1 200 OK
Date: Thu, 04 Jan 2018 16:25:05 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 04 Jan 2018 16:16:30 GMT
ETag: "2ddc-561f5a7951380"
Accept-Ranges: bytes
Content-Length: 11740
Via: 1.1 fmdmzpr06, 1.1 fmintpr02
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Age: 0

Get:11 http://security.ubuntu.com/ubuntu artful-security/universe Translation-en [11.7 kB]
Reading package lists... Done
E: The repository 'https://download.docker.com/linux/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@singlevm:/etc/apt# sudo apt-get update -o Debug::Acquire::http=True -o Debug::Acquire::https=True > LOG
GET http://archive.ubuntu.com/ubuntu/dists/artful/InRelease HTTP/1.1
Host: archive.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
If-Modified-Since: Thu, 19 Oct 2017 12:56:35 GMT
User-Agent: Debian APT-HTTP/1.3 (1.5.1)


GET http://security.ubuntu.com/ubuntu/dists/artful-security/InRelease HTTP/1.1
Host: security.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
If-Modified-Since: Thu, 04 Jan 2018 16:22:00 GMT
User-Agent: Debian APT-HTTP/1.3 (1.5.1)


Answer for: http://archive.ubuntu.com/ubuntu/dists/artful/InRelease
HTTP/1.1 200 OK
Date: Thu, 04 Jan 2018 16:25:34 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 19 Oct 2017 12:56:35 GMT
ETag: "39c6b-55be5e2d806c0"
Accept-Ranges: bytes
Content-Length: 236651
Cache-Control: max-age=0, proxy-revalidate
Expires: Thu, 04 Jan 2018 16:25:34 GMT
Via: 1.1 fmdmzpr06, 1.1 fmintpr02
Proxy-Connection: Keep-Alive
Connection: Keep-Alive

Answer for: http://security.ubuntu.com/ubuntu/dists/artful-security/InRelease
HTTP/1.1 304 Not Modified
Date: Thu, 04 Jan 2018 16:25:34 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 04 Jan 2018 16:22:00 GMT
ETag: "132fd-561f5bb407a00"
Accept-Ranges: bytes
Cache-Control: max-age=3085, s-maxage=3300, proxy-revalidate
Expires: Thu, 04 Jan 2018 17:20:34 GMT
Via: 1.1 fmdmzpr06, 1.1 fmintpr02
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Age: 0

GET http://archive.ubuntu.com/ubuntu/dists/artful-updates/InRelease HTTP/1.1
Host: archive.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
If-Modified-Since: Thu, 04 Jan 2018 16:07:00 GMT
User-Agent: Debian APT-HTTP/1.3 (1.5.1)


Answer for: http://archive.ubuntu.com/ubuntu/dists/artful-updates/InRelease
HTTP/1.1 200 OK
Date: Thu, 04 Jan 2018 16:25:35 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 04 Jan 2018 16:22:00 GMT
ETag: "132fb-561f5bb407a00"
Accept-Ranges: bytes
Content-Length: 78587
Cache-Control: max-age=1584, proxy-revalidate
Expires: Thu, 04 Jan 2018 16:51:59 GMT
Via: 1.1 fmdmzpr06, 1.1 fmintpr02
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Age: 0

GET http://archive.ubuntu.com/ubuntu/dists/artful-backports/InRelease HTTP/1.1
Host: archive.ubuntu.com
Cache-Control: max-age=0
Accept: text/*
If-Modified-Since: Thu, 04 Jan 2018 16:07:00 GMT
User-Agent: Debian APT-HTTP/1.3 (1.5.1)


Answer for: http://archive.ubuntu.com/ubuntu/dists/artful-backports/InRelease
HTTP/1.1 200 OK
Date: Thu, 04 Jan 2018 16:25:35 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Thu, 04 Jan 2018 16:22:00 GMT
ETag: "119fe-561f5bb407a00"
Accept-Ranges: bytes
Content-Length: 72190
Cache-Control: max-age=1584, proxy-revalidate
Expires: Thu, 04 Jan 2018 16:51:59 GMT
Via: 1.1 fmdmzpr06, 1.1 fmintpr02
Proxy-Connection: Keep-Alive
Connection: Keep-Alive
Age: 0

E: The repository 'https://download.docker.com/linux/ubuntu artful Release' does not have a Release file.

**Comment by GabyCT** [comment]
@jodh-intel , I can perform a $apt-get update, but not when I am adding the docker repository

**Comment by jodh-intel** [comment]
Hi @GabyCT - there must be something odd about that system because the error you get is patently incorrect:

```
E: The repository 'https://download.docker.com/linux/ubuntu artful Release' does not have a Release file.
```

- https://download.docker.com/linux/ubuntu/dists/artful/Release

I'd double-check proxy settings and if necessary do a clean re-install.

**Comment by devimc** [comment]
it works for me

@GabyCT could you try again using ccloudvm?

```
rm -rf ~/.ccloudvm
GOPATH/bin/ccloudvm create artful
GOPATH/bin/ccloudvm connect
sudo -E apt-get -y install apt-transport-https ca-certificates wget software-properties-common
wget -qO - https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo -E add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo -E apt-get update
sudo -E apt-get -y install docker-ce
```

**Comment by GabyCT** [comment]
@devimc , thanks that worked :)
